apiVersion: kubeadm.k8s.io/v1beta4
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 10.67.38.87
  bindPort: 6443
nodeRegistration:
  criSocket: unix:///run/containerd/containerd.sock
  kubeletExtraArgs:
    - name: node-ip
      value: 10.67.38.87
---
apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
apiServer:
  certSANs:
    - 127.0.0.1
    - localhost
    - 10.67.38.40
    - 10.67.38.87
    - 10.67.38.221
    - 10.67.38.211
networking:
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.96.0.0/16
controlPlaneEndpoint: "10.67.38.40:6443"
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
conntrack:
  maxPerCore: 0
  min: 0
